<?php

use Illuminate\Database\Seeder;

class presenceseeder extends Seeder
{
    
    public function run()
    {
        DB::table('presence')->insert([
            [
                'class_id'=>'TSI203-01',
                'student_id'=>'24',
                'examtype_id'=>'2',
                'status'=>0,
                'code'=>'abcd12'
            ],
            [
                'class_id'=>'TSI203-02',
                'student_id'=>'25',
                'examtype_id'=>'2',
                'status'=>0,
                'code'=>'abcd123'
            ],
            [
                'class_id'=>'TSI309-01',
                'student_id'=>'14',
                'examtype_id'=>'2',
                'status'=>0,
                'code'=>'abcd1234'
            ],
            [
                'class_id'=>'TSI309-02',
                'student_id'=>'15',
                'examtype_id'=>'2',
                'status'=>0,
                'code'=>'abcd12345'
            ],
            [
                'class_id'=>'TSI203-01',
                'student_id'=>'26',
                'examtype_id'=>'2',
                'status'=>0,
                'code'=>'abcd123456'
            ],
            [
                'class_id'=>'TSI203-01',
                'student_id'=>'28',
                'examtype_id'=>'2',
                'status'=>0,
                'code'=>'abcd1234567'
            ],
            [
                'class_id'=>'TSI203-01',
                'student_id'=>'30',
                'examtype_id'=>'2',
                'status'=>0,
                'code'=>'abcd12345678'
            ],
            [
                'class_id'=>'TSI203-01',
                'student_id'=>'32',
                'examtype_id'=>'2',
                'status'=>0,
                'code'=>'abcd123456789'
            ],
            [
                'class_id'=>'TSI203-02',
                'student_id'=>'27',
                'examtype_id'=>'2',
                'status'=>0,
                'code'=>'abcd12345678910'
            ],
            [
                'class_id'=>'TSI203-02',
                'student_id'=>'29',
                'exam_type'=>'2',
                'status'=>0,
                'code'=>'abc12'
            ],
            [
                'class_id'=>'TSI203-02',
                'student_id'=>'31',
                'exam_type'=>'2',
                'status'=>0,
                'code'=>'abc123'
            ],
            [
                'class_id'=>'TSI203-02',
                'student_id'=>'33',
                'exam_type'=>'2',
                'status'=>0,
                'code'=>'abc1234'
            ],
            [
                'class_id'=>'TSI309-01',
                'student_id'=>'16',
                'exam_type'=>'2',
                'status'=>0,
                'code'=>'abc12345'
            ],
            [
                'class_id'=>'TSI309-01',
                'student_id'=>'18',
                'exam_type'=>'2',
                'status'=>0,
                'code'=>'abc123456'
            ],
            [
                'class_id'=>'TSI309-01',
                'student_id'=>'20',
                'exam_type'=>'2',
                'status'=>0,
                'code'=>'abc1234567'
            ],
            [
                'class_id'=>'TSI309-01',
                'student_id'=>'22',
                'exam_type'=>'2',
                'status'=>0,
                'code'=>'abc12345678'
            ],
            [
                'class_id'=>'TSI309-02',
                'student_id'=>'17',
                'exam_type'=>'2',
                'status'=>0,
                'code'=>'abc123456789'
            ],
            [
                'class_id'=>'TSI309-02',
                'student_id'=>'19',
                'exam_type'=>'2',
                'status'=>0,
                'code'=>'abc12345678910'
            ],
            [
                'class_id'=>'TSI309-02',
                'student_id'=>'21',
                'exam_type'=>'2',
                'status'=>0,
                'code'=>'ab12'
            ],
            [
                'class_id'=>'TSI309-02',
                'student_id'=>'23',
                'exam_type'=>'2',
                'status'=>0,
                'code'=>'ab123'
            ],
        ]);
    }
}
